#!/bin/sh

[ "$1" = "" ] && {
  echo usage: cdrip \<dir\> >&2
  exit 1
}

mkdir -p "$1"
cd "$1" || exit

# regular
cdparanoia -B

# disable paranoia
# cdparanoia -BYZ

for i in *.wav; do
  # 320 kbit/s
  ffmpeg -i "$i" -c:a libmp3lame -b:a 320k "$i.mp3"

  # variable bitrate
  # ffmpeg -i $i -c:a libmp3lame -qscale:a 2 $i.mp3
done
