#!/bin/bash
# qlist -e "$@" | xargs scanelf -L -n -q -F '%n #F' | tr , ' ' | xargs qfile -Cv | awk '{print $1}' | uniq
qlist -e "$@" | xargs scanelf -L -n -q -F '%n #F' | tr , ' ' | xargs qfile -Cv | awk '{ gsub(":", "", $1); print $1}' | uniq
